services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: knu-chatbot
      MYSQL_USER: knu-chatbot_user
      MYSQL_PASSWORD: knu-chatbot123
      MYSQL_ROOT_PASSWORD: knu-chatbot123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "knu-chatbot_user", "--password=knu-chatbot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/knu-chatbot?allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits: # 상한
          cpus: '2'
          memory: 1G
        reservations: # 하한
          cpus: '0.5'
          memory: 512M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  mysql_data:
  grafana_data:

networks:
  dev: