services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: knu-chatbot
      MYSQL_USER: knu-chatbot_user
      MYSQL_PASSWORD: knu-chatbot123
      MYSQL_ROOT_PASSWORD: knu-chatbot123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "knu-chatbot_user", "--password=knu-chatbot123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2GB

  redis:
    image: redis:latest
    container_name: redis-session
    ports:
      - "6379:6379"
    networks:
      - dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/knu-chatbot?allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      - promtail_data:/logs
    deploy:
      resources:
        limits: # 상한
          cpus: '2'
          memory: 1G
        reservations: # 하한
          cpus: '0.5'
          memory: 512M
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    restart: unless-stopped # 중지되면 자동으로 다시 재시작
    volumes:
      - promtail_data:/logs:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./promtail/positions:/tmp
    networks:
      - dev
    command:
      - --config.file=/etc/promtail/promtail-config.yaml

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    user: root
    volumes:
      - ./loki/data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - dev
    command:
      - --config.file=/etc/loki/loki-config.yaml

volumes:
  mysql_data:
  redis_data:
  grafana_data:
  promtail_data:

networks:
  dev: