apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      containers:
        - name: my-webserver
          image: dgh0001/knuchatbot:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: web-config