server:
  http_listen_port: 8080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - app
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: app
    static_configs:
        - targets:
          - app
          labels:
            job: applogs
            __path__: /logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            threadName: threadName
            loggerName: loggerName
            message: message
            stacktrace: stacktrace
      - labels:
          level: ''
          endpoint: ''
          instanceId: ''
          httpMethod: ''
          memberId: ''
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000-0700"