name: cd pipeline

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build code
        run: ./gradlew clean build

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set image tags
        id: vars
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/knuchatbot:${{ steps.vars.outputs.GIT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/knuchatbot:latest

      - name: set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: deploy to server
        run: kubectl set image deployment/hostname-deployment \
          my-webserver=${{ secrets.DOCKER_USERNAME }}/knuchatbot:${{ steps.vars.outputs.GIT_SHA }} \
          --kubeconfig ~/.kube/config

      - name: wait for rollout
        run: kubectl rollout status deployment/hostname-deployment --timeout=180s --kubeconfig ~/.kube/config